### PR TITLE
dev -> main

### PR DESCRIPTION
**Pull request by m7pr**
Mergind dev to main after #151 was introduced

### CODE REVIEW

**Comment by m7pr** [comment]
@vedhav tried to sync `dev` with `main` but they are 346 commits appart?

**Comment by vedhav** [comment]
Hey @m7pr Sent another PR #153 to do this, Can you please review it? We needed to branch off of `dev` for this merge as we will need `dev` branch after the merge.

**Comment by m7pr** [comment]
ah, got it sorry! will remember for future!

**Comment by vedhav** [comment]
> ah, got it sorry! will remember for future!

Don't be :) It's not mentioned anywhere in the docs 🤦🏽 I should write about it somewhere.

**Pull request closed without merging**
