### PR TITLE
Explicitly add favicon and browser tab title

### LINKED ISSUE #64: [Bug]: shinyapps.io deployment does not have the favicon
### What happened?

Related to the [comment](https://github.com/insightsengineering/teal.gallery/issues/55#issuecomment-1682007029).

Even after adding a favicon image in the static files directory shinyapps.io does not automatically detect and add it to the browser tab.

P.S We should also have a good title in the browser tab.

Screenshot 2023-08-31 at 3 32 12 PM

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by vedhav**
Closes #64 

Right now the browse titles for the apps are as follows:

1. basic-teal - Basic Teal
2. exploratory - Exploratory
3. safety - Safety
4. efficacy - Efficacy
5. patient-profile - Patient Profile
6. early-dev - Early dev
7. longitudinal - Longitudinal
8. RNA-seq - RNA seq
9. python - Python

### CODE REVIEW

**Comment by chlebowa** [comment]
How about adding "App" to those titles? Also, "Early dev" sounds jargony, could the title be a little more formal, e.g. "Early Development (App)"?

**Comment by lcd2yyz** [comment]
Suggestions:
basic-teal = Basic Teal Demo App
exploratory = Exploratory Analysis Teal Demo App
safety = Safety Analysis Teal Demo App
efficacy = Efficacy Analysis Teal Demo App
patient-profile = Patient Profile Analysis Teal Demo App
early-dev = Early Development Analysis Teal Demo App
longitudinal = Longitudinal Analysis Teal Demo App
RNA-seq = RNA-Seq Analysis Teal Demo App
python = Python Dataset Teal Demo App

**Comment by chlebowa** [comment]
With "Demo" it seems more natural to me to say "Teal Demo App: Patient Profile". What do you think @lcd2yyz?

**Comment by lcd2yyz** [comment]
> With "Demo" it seems more natural to me to say "Teal Demo App: Patient Profile". What do you think @lcd2yyz?

Thanks for sharing your thoughts. Initially I was going with the title you suggested as well. But then I remembered that if user has multiple tabs open, and the tab title will get truncated. Then all users will see are just "Teal Demo A..." (for example) uniformly across all tabs. So putting the info about the content first will help a bit to differentiate.

**Comment by chlebowa** [comment]
OK then.

**Pull request merged**
